name: Deploy to Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy files
        run: |
          # Define the directory on the self-hosted runner where you want to deploy the files
          DEPLOY_DIR=/root/ise-pick/pb_migrations

          # Remove any existing files in the deploy directory
          rm -rf ${DEPLOY_DIR}/*

          # Copy the files from the current commit to the deploy directory
          cp -r ./backend/pb_migrations ${DEPLOY_DIR}/
